### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by JohnMcLear** [pcwii/usb-music#4]
IE Apache2 :)

Thanks!

**Comment by pcwii** [comment]
The project is currently assigned a GPL-3.0 License (added 7 days ago ;-).
![image](https://user-images.githubusercontent.com/30759206/117812305-a6686a80-b22f-11eb-955a-507241a17f25.png)

**Comment by JohnMcLear** [comment]
So it is! :D  It was mycroft who was complaining about a lack of license but it might have been a cached page etc :)
