### ISSUE TITLE
Pause in initial music playback

### ISSUE THREAD

**Issue by JohnMcLear** [pcwii/usb-music#5]
After playing any music from usb-music I get an initial second of audio then a half second silence then the song keeps playing.  Any idea where to dig for logs?

```
2021-05-11 11:10:51.594 | INFO     |   803 | mycroft.audio.speech:mute_and_speak:127 | Speak: Now playing your music selection
Playing WAVE '/tmp/mycroft/cache/tts/Mimic/9faa11fec00d5afd5b3341274a29258c.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono
```
Is all I see that is even slightly related to music playback.

This happens once at the same time on each song that is played.

**Comment by pcwii** [comment]
try to ssh into your device then drop out of the mycroft-cli-client with ^C at the prompt issue the following command.
`tail -f /var/log/mycroft/skills.log | grep usb-music`
This will show the mycroft logs specifically related to the usb-music skill as they are generated.
Lastly play some music and see if any logs are generated when you get the half second silence.

**Comment by JohnMcLear** [comment]
The only weird thing I see here is that doing "my music" shows a lot of music (possibly adding to a queue).

I'm not seeing anything in the log that might relate to why songs would start then pause, then continue playing ;\  I am doubting it's related to the plugin, I imagine it's related to raspberry pi.

Yea confirmed it's a pi issue..  If I do ``vlc filelocation`` ``play`` I experience the same issue.  Pi 4 too so can't be lack of cpu..
  I tried copying the file from the usb stick to the sdcard and the issue persists so it's not a usb file read speed issue.

A suggestion it's due to pulseaudio: https://www.raspberrypi.org/forums/viewtopic.php?t=306892

**Comment by pcwii** [comment]
interesting, I am running the skill on a pi3 and I don't have this issue. Is there something I can look into on my end to see if there is a difference?
Are all your files mp3? most of mine are Flac,maybe that's the difference.
if all your files are mp3, I could add a configuration option to use the mycroft default mpg123 player (only does mp3).

**Comment by JohnMcLear** [comment]
```
mpg123 ~/test.mp3 
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
```
Totally stable playback, so it must be a VLC issue..  Maybe we should make mpg123 an optional checkbox item in skill settings?

Oh hello: https://www.raspberrypi.org/forums/viewtopic.php?t=293569

**Comment by JohnMcLear** [comment]
Fixed in pulseaudio config.
File: ``/etc/pulse/daemon.conf`` 
Changed to Value: ``default-fragment-size-msec = 15``

To restart pulseaudio: ``pulseaudio -k && pulseaudio-D``
To test: ``vlc test.mp3``

Works :)

**Comment by pcwii** [comment]
> Fixed in pulseaudio config.
> File: `/etc/pulse/daemon.conf`
> Changed to Value: `default-fragment-size-msec = 15`
> 
> To restart pulseaudio: `pulseaudio -k && pulseaudio-D`
> To test: `vlc test.mp3`
> 
> Works :)

Going to add this to a troubleshooting section of the readme.md
